### ISSUE TITLE
(rules): S3_BUCKET_SSL_REQUESTS_ONLY checks too literally

### ISSUE THREAD

**Issue by benbridts** [aws-cloudformation/aws-guard-rules-registry#218]
### What is the problem?

S3_BUCKET_SSL_REQUESTS_ONLY fails even in cases where it should't

### Reproduction Steps

I'm using
```
docker run \
  --rm \
  -v $(pwd):/src:rw,Z \
  --workdir /src \
  public.ecr.aws/r7q6h7y6/guard:1.0.1 \
  cfn-guard validate -r /wa-Security-Pillar.guard -d test.yaml
```
to test these three templates

```
# template 1
Resources:
  Bucket:
    Metadata: 
      guard:
        SuppressedRules:
          - S3_BUCKET_LEVEL_PUBLIC_ACCESS_PROHIBITED
          - S3_BUCKET_PUBLIC_READ_PROHIBITED
          - S3_BUCKET_PUBLIC_WRITE_PROHIBITED
          - S3_BUCKET_LOGGING_ENABLED
          - S3_BUCKET_SERVER_SIDE_ENCRYPTION_ENABLED
          - S3_DEFAULT_ENCRYPTION_KMS
          - S3_BUCKET_VERSIONING_ENABLED

    Type: AWS::S3::Bucket
  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref Bucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Deny
            Action: "s3:*"
            Principal: "*"
            Resource: "*"
            Condition:
              Bool:
                "aws:SecureTransport": false
```
```
# template 2
Resources:
  Bucket:
    Metadata: 
      guard:
        SuppressedRules:
          - S3_BUCKET_LEVEL_PUBLIC_ACCESS_PROHIBITED
          - S3_BUCKET_PUBLIC_READ_PROHIBITED
          - S3_BUCKET_PUBLIC_WRITE_PROHIBITED
          - S3_BUCKET_LOGGING_ENABLED
          - S3_BUCKET_SERVER_SIDE_ENCRYPTION_ENABLED
          - S3_DEFAULT_ENCRYPTION_KMS
          - S3_BUCKET_VERSIONING_ENABLED

    Type: AWS::S3::Bucket
  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref Bucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: EnforceTls
            Effect: Deny
            Action: "s3:*"
            Principal: "*"
            Resource: "*"
            Condition:
              Bool:
                "aws:SecureTransport": false
```
```
# template 3
Resources:
  Bucket:
    Metadata: 
      guard:
        SuppressedRules:
          - S3_BUCKET_LEVEL_PUBLIC_ACCESS_PROHIBITED
          - S3_BUCKET_PUBLIC_READ_PROHIBITED
          - S3_BUCKET_PUBLIC_WRITE_PROHIBITED
          - S3_BUCKET_LOGGING_ENABLED
          - S3_BUCKET_SERVER_SIDE_ENCRYPTION_ENABLED
          - S3_DEFAULT_ENCRYPTION_KMS
          - S3_BUCKET_VERSIONING_ENABLED

    Type: AWS::S3::Bucket
  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref Bucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: DeleteProtection
            Action: s3:Delete*
            Effect: Deny
            Principal: '*'
            Resource:
              - !GetAtt Bucket.Arn
              - !Sub "${Bucket.Arn}/*"
          - Sid: EnforceTls
            Effect: Deny
            Action: "s3:*"
            Principal: "*"
            Resource: "*"
            Condition:
              Bool:
                "aws:SecureTransport": false
```

### What did you expect to happen?

I'd expect all commands to run without errors, as the TLS enforcement is present in all three

### What actually happened?

Only the first one runs without errors, the others give

```
# template 2
Other
test.yaml Status = FAIL
FAILED rules
wa-Security-Pillar.guard/S3_BUCKET_SSL_REQUESTS_ONLY                    FAIL
---
Evaluating data test.yaml against rules wa-Security-Pillar.guard
Number of non-compliant resources 1
Resource = BucketPolicy {
  Type      = AWS::S3::BucketPolicy
  Rule = S3_BUCKET_SSL_REQUESTS_ONLY {
    ALL {
      Check =  %s3_buckets_policies_ssl_requests_only[*].Properties.PolicyDocument.Statement.* EQUALS  {"Action":"s3:*","Effect":"Deny","Principal":"*","Resource":"*","Condition":{"Bool":{"aws:SecureTransport":false}}} {
        ComparisonError {
          Message          {
            Guard Rule Set: wa-Security-Pillar
            Controls: SEC-9.3,SEC-9.4
            Violation: Bucket policies must feature a statement to enforce TLS usage.
            Fix: Set a bucket policy statement to '"Action":"s3:*","Effect":"Deny","Principal":"*","Resource":"*","Condition":{"Bool":{"aws:SecureTransport":false}}' .
          }
          Error           = Check was not compliant as property value [Path=/Resources/BucketPolicy/Properties/PolicyDocument/Statement/0[L:22,C:15] Value={"Sid":"EnforceTls","Effect":"Deny","Action":"s3:*","Principal":"*","Resource":"*","Condition":{"Bool":{"aws:SecureTransport":false}}}] not equal to value [Path=[L:0,C:0] Value={"Action":"s3:*","Effect":"Deny","Principal":"*","Resource":"*","Condition":{"Bool":{"aws:SecureTransport":false}}}].
          PropertyPath    = /Resources/BucketPolicy/Properties/PolicyDocument/Statement/0[L:22,C:15]
          Operator        = EQUAL
          Value           = {"Sid":"EnforceTls","Effect":"Deny","Action":"s3:*","Principal":"*","Resource":"*","Condition":{"Bool":{"aws:SecureTransport":false}}}
          ComparedWith    = {"Action":"s3:*","Effect":"Deny","Principal":"*","Resource":"*","Condition":{"Bool":{"aws:SecureTransport":false}}}
          Code:
               20.        Version: '2012-10-17'
               21.        Statement:
               22.          - Sid: EnforceTls
               23.            Effect: Deny
               24.            Action: "s3:*"
               25.            Principal: "*"

        }
      }
    }
  }
}
```
and
```
# template 3
Other
test.yaml Status = FAIL
FAILED rules
wa-Security-Pillar.guard/S3_BUCKET_SSL_REQUESTS_ONLY                    FAIL
---
Evaluating data test.yaml against rules wa-Security-Pillar.guard
Number of non-compliant resources 1
Resource = BucketPolicy {
  Type      = AWS::S3::BucketPolicy
  Rule = S3_BUCKET_SSL_REQUESTS_ONLY {
    ALL {
      Check =  %s3_buckets_policies_ssl_requests_only[*].Properties.PolicyDocument.Statement.* EQUALS  {"Action":"s3:*","Effect":"Deny","Principal":"*","Resource":"*","Condition":{"Bool":{"aws:SecureTransport":false}}} {
        ComparisonError {
          Message          {
            Guard Rule Set: wa-Security-Pillar
            Controls: SEC-9.3,SEC-9.4
            Violation: Bucket policies must feature a statement to enforce TLS usage.
            Fix: Set a bucket policy statement to '"Action":"s3:*","Effect":"Deny","Principal":"*","Resource":"*","Condition":{"Bool":{"aws:SecureTransport":false}}' .
          }
          Error           = Check was not compliant as property value [Path=/Resources/BucketPolicy/Properties/PolicyDocument/Statement/0[L:22,C:15] Value={"Sid":"DeleteProtection","Action":"s3:Delete*","Effect":"Deny","Principal":"*","Resource":[{"Fn::GetAtt":"Bucket.Arn"},{"Fn::Sub":"${Bucket.Arn}/*"}]}] not equal to value [Path=[L:0,C:0] Value={"Action":"s3:*","Effect":"Deny","Principal":"*","Resource":"*","Condition":{"Bool":{"aws:SecureTransport":false}}}].
          PropertyPath    = /Resources/BucketPolicy/Properties/PolicyDocument/Statement/0[L:22,C:15]
          Operator        = EQUAL
          Value           = {"Sid":"DeleteProtection","Action":"s3:Delete*","Effect":"Deny","Principal":"*","Resource":[{"Fn::GetAtt":"Bucket.Arn"},{"Fn::Sub":"${Bucket.Arn}/*"}]}
          ComparedWith    = {"Action":"s3:*","Effect":"Deny","Principal":"*","Resource":"*","Condition":{"Bool":{"aws:SecureTransport":false}}}
          Code:
               20.        Version: '2012-10-17'
               21.        Statement:
               22.          - Sid: DeleteProtection
               23.            Action: s3:Delete*
               24.            Effect: Deny
               25.            Principal: '*'

        }
      }
      Check =  %s3_buckets_policies_ssl_requests_only[*].Properties.PolicyDocument.Statement.* EQUALS  {"Action":"s3:*","Effect":"Deny","Principal":"*","Resource":"*","Condition":{"Bool":{"aws:SecureTransport":false}}} {
        ComparisonError {
          Message          {
            Guard Rule Set: wa-Security-Pillar
            Controls: SEC-9.3,SEC-9.4
            Violation: Bucket policies must feature a statement to enforce TLS usage.
            Fix: Set a bucket policy statement to '"Action":"s3:*","Effect":"Deny","Principal":"*","Resource":"*","Condition":{"Bool":{"aws:SecureTransport":false}}' .
          }
          Error           = Check was not compliant as property value [Path=/Resources/BucketPolicy/Properties/PolicyDocument/Statement/1[L:29,C:15] Value={"Sid":"EnforceTls","Effect":"Deny","Action":"s3:*","Principal":"*","Resource":"*","Condition":{"Bool":{"aws:SecureTransport":false}}}] not equal to value [Path=[L:0,C:0] Value={"Action":"s3:*","Effect":"Deny","Principal":"*","Resource":"*","Condition":{"Bool":{"aws:SecureTransport":false}}}].
          PropertyPath    = /Resources/BucketPolicy/Properties/PolicyDocument/Statement/1[L:29,C:15]
          Operator        = EQUAL
          Value           = {"Sid":"EnforceTls","Effect":"Deny","Action":"s3:*","Principal":"*","Resource":"*","Condition":{"Bool":{"aws:SecureTransport":false}}}
          ComparedWith    = {"Action":"s3:*","Effect":"Deny","Principal":"*","Resource":"*","Condition":{"Bool":{"aws:SecureTransport":false}}}
          Code:
               27.              - !GetAtt Bucket.Arn
               28.              - !Sub "${Bucket.Arn}/*"
               29.          - Sid: EnforceTls
               30.            Effect: Deny
               31.            Action: "s3:*"
               32.            Principal: "*"

        }
      }
    }
  }
}
```

### CloudFormation Guard Version

cfn-guard 2.1.0

### OS

MacOS / Docker
